<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <AssemblyName>WindowsComplianceChecker.DAL</AssemblyName>
    <RootNamespace>WindowsComplianceChecker.DAL</RootNamespace>
    <LangVersion>7.3</LangVersion>
    <Nullable>disable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <!-- JSON 序列化 -->
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\WindowsComplianceChecker.Contracts\WindowsComplianceChecker.Contracts.csproj" />
  </ItemGroup>

</Project>
